extend type Query {
    getHousesForSaleListings(
        city: String
        state: String
        zipcode: String
        page: Int!
        limit: Int!
        preferences: HouseDetails
    ): HouseForSaleListingResponse!
}

type HouseDetails {
    bedrooms: Int
    bathrooms: Int
    minPrice: Float
    maxPrice: Float
    minSize: Int
    maxSize: Int
}
type HouseForSaleListingResponse {
    data: [HouseForSaleListing]
    message: String!
}
type HouseForSaleListing {
    title: String!
    description: String!
    url: AWSURL!
}