extend type Mutation{
    createRealtor(input: CreateRealtorInput!): RealtorResponse
    deleteRealtor(PK: ID!, SK: ID!): RealtorResponse
    createSellerCustomer(input: CreateSellerCustomerInput!): SellerCustomerResponse
}
extend type Query {
    getRealtor: RealtorResponse
}

# General Data Types
interface Response {
    
    message: String
}

## Realtor endpoints
input CreateRealtorInput {
    name: String!
    midddleName: String
    lastName: String!
    email: String!
    phone: String!
    agentType: String!
    operationAreas: [String]!
    languages: [String]!
    communicationStyles: [String]!
    realEstateCompany: String!
    corporativeColors: [String]!
}

type Realtor {
    PK: String!
    SK: String!
    name: String!
    midddleName: String
    lastName: String!
    email: String!
    phone: String!
    agentTyype: String!
    operationAreas: [String]!
    languages: [String]!
    communicationStyles: [String]!
    realEstateCompany: String!
    corporativeColors: [String]!
}

type RealtorResponse implements Response {
    data: Realtor
    message: String
}

## Customer endpoints

enum CustomerType {
    SELLER
    BUYER
    LANDLORD
    TENANT
    INVESTOR
}
input CreateSellerCustomerInput {
    name: String!
    midddleName: String
    lastName: String!
    email: String!
    phone: String!
    preferredContactMethod: String!
    preferredLanguage: String!
    customerType: CustomerType!
    labels: [String]
}

# type FinancialProfile {
#     budget: Float
#     preferredPaymentMethod: String
#     downPayment: Float
#     ##TODO financing data
# }

type Address {
    street: String
    city: String
    state: String
    zipCode: String
}

enum PropertyStatus {
    NEW
    USED
    REFURBISHED
    UNDER_CONSTRUCTION
}
# type PropertyPreferences {
#     zones: [Address]
#     yearBuiltRangeMin: Int
#     yearBuiltRangeMax: Int
#     propertyStatus: [PropertyStatus]
#     #TODO: Community preferences
#     #TODO: School preferences
#     noOfBedroomsMin: Int
#     noOfBedroomsMax: Int
#     noOfBathroomsMin: Int
#     noOfBathroomsMax: Int
#     minSquareFeet: Int
#     maxSquareFeet: Int
#     minLotSize: Int
#     maxLotSize: Int
#     generalDescriptions: String
# }
# input CreateBuyerCustomerInput {
#     name: String!
#     midddleName: String
#     lastName: String!
#     email: String!
#     phone: String!
#     preferredContactMethod: String!
#     preferredLanguage: String!
#     customerType: CustomerType!
#     labels: [String]
#     financialProfile: FinancialProfile
#     propertyPreferences: PropertyPreferences
# }

type SellerCustomer {
    PK: String!
    SK: String!
    name: String!
    midddleName: String
    lastName: String!
    email: String!
    phone: String!
    preferredContactMethod: String!
    preferredLanguage: String!
    customerType: CustomerType!
    labels: [String]
}
type SellerCustomerResponse implements Response {
    data: SellerCustomer
    message: String
}