extend type Mutation{
    createRealtor(input: CreateRealtorInput!): RealtorResponse
}
extend type Query {
    getRealtor(PK: ID!, SK: ID!): RealtorResponse
}

input CreateRealtorInput {
    name: String!
    midddleName: String
    lastName: String!
    email: String!
    phone: String!
    agentTyype: String!
    operationAreas: [String]!
    languages: [String]!
    communicationStyles: [String]!
    realEstateCompany: String!
    corporativeColors: [String]!
}

type Realtor {
    PK: ID!
    SK: ID!
    name: String!
    midddleName: String
    lastName: String!
    email: String!
    phone: String!
    agentTyype: String!
    operationAreas: [String]!
    languages: [String]!
    communicationStyles: [String]!
    realEstateCompany: String!
    corporativeColors: [String]!
}

type RealtorResponse {
    data: Realtor
    message: String
}