# "org" ensures this Service is used with the correct Serverless Framework Access Key.
org: eprimelles
# "app" enables Serverless Framework Dashboard features and sharing them with other Services.
app: estateengine
# "service" is the name of this project. This will also be added to your AWS resource names.
service: estatengine-backend

provider:
  name: aws
  runtime: nodejs20.x
  stage: ${sls:stage}

plugins:
  - serverless-appsync-plugin

parameters:
  STAGE:
    type: string
    default: prod
    description: The stage to deploy to (e.g., dev, prod)

appsync:
  # TODO: Add Caching, WAF, Domain, authentication, etc.
  name: ${self:service}-${STAGE}
  schema: appsync/schema.graphql
  authentication:
    type: API_Key
  apiKeys:
    - name: ${self:service}-${STAGE}-api-key
      description: API Key for ${self:service} in ${self:provider.stage} stage
      expires: 1Y # Example expiration date, adjust as needed
  
  datasources:
    - ${file(appsync/datasources/mock.yml)}
  resolvers:
    - ${file(appsync/resolvers/resolvers.yml)}

functions:
  hello:
    handler: handler.hello
