AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  drivestate-estatengine-backend

  Sample SAM Template for estatengine-backend

Parameters:
  Stage:
    Type: String
    Default: dev
    AllowedValues:
      - dev
      - prod
    Description: The stage for the application (dev or prod)
    ConstraintDescription: Must be either dev or prod.
Resources:
  EstatengineBackendTable:
    Type: AWS::Serverless::SimpleTable
    Properties:
      TableName:
        Fn::Join:
          - '-'
          - - 'estatengine-backend'
            - !Ref Stage
      PrimaryKey:
        Name: PK
        Type: String     


  # Greeter:
  #   Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
  #   Properties:
  #     CodeUri: greeter/
  #     Handler: app.lambdaHandler
  #     Runtime: nodejs22.x
  #     Architectures:
  #     - x86_64

  EstatengineGraphQLApi:
    Type: AWS::Serverless::GraphQLApi
    Properties:
      Name: !Sub 'estatengine-backend-gqlapi-${Stage}'
      SchemaUri: ./gql/schema.graphql
      Auth:
        Type: API_KEY
      ApiKeys:
        MyApiKey:
          Description: my api key
      DataSources: 
        DynamoDb:
          EstatengineBackendTable:
            TableName: !Ref EstatengineBackendTable
            TableArn: !GetAtt EstatengineBackendTable.Arn 
       
      Functions:
        processCustomer:
          Runtime:
            Name: APPSYNC_JS
            Version: 1.0.0
          DataSource: NONE
          CodeUri: ./gql/functions/processCustomer.js
        createcustomer:
          Runtime:
            Name: APPSYNC_JS
            Version: 1.0.0
          DataSource: EstatengineBackendTable
          CodeUri: ./gql/functions/createCustomer.js
        
      Resolvers:
        Mutation:
          createCustomer:
            Runtime:
              Name: APPSYNC_JS
              Version: 1.0.0
            Pipeline:
            - processCustomer
            - createCustomer
        


  ApplicationResourceGroup:
    Type: AWS::ResourceGroups::Group
    Properties:
      Name:
        Fn::Sub: ApplicationInsights-SAM-${AWS::StackName}
      ResourceQuery:
        Type: CLOUDFORMATION_STACK_1_0
  ApplicationInsightsMonitoring:
    Type: AWS::ApplicationInsights::Application
    Properties:
      ResourceGroupName:
        Ref: ApplicationResourceGroup
      AutoConfigurationEnabled: 'true'
Outputs:
  HelloWorldGraphQLApi:
    Description: HelloWorldGraphQLApi endpoint URL for Prod environment
    Value: !GetAtt HelloWorldGraphQLApi.GraphQLUrl
  HelloWorldGraphQLApiMyApiKey:
    Description: API Key for HelloWorldGraphQLApi
    Value: !GetAtt HelloWorldGraphQLApiMyApiKey.ApiKey

# # More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Tracing: Active
    # You can add LoggingConfig parameters such as the Logformat, Log Group, and SystemLogLevel or ApplicationLogLevel. Learn more here https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/sam-resource-function.html#sam-function-loggingconfig.
    LoggingConfig:
      LogFormat: JSON
  Api:
    TracingEnabled: true
