schema {
  query: Query
  mutation: Mutation
}

type Query {
 
}

type Mutation {
  createCustomer(customerId: String!, customerName: String!, agency: String!, realtorSpeciality: [Specialities]!, languages [String], experience: Int, phone: Phones
                  communicationWays : CommWays): Customer!
}

enum Specialities {
 RESIDENTIAL
 COMMERCIAL
 INVESTMENT
}
enum CommWays {
  EMAIL
  PHONE
  SMS
  WHATSAPP
}
type Phone {
  alias: String,
  countryCode: String,
  number: String
  extension: String
  isPrimary: Boolean
}
type Customer{
  id: String!
  author: String
  title: String
  content: String
  ups: Int!
  downs: Int!
  version: Int!
}
