openapi: 3.0.1
info:
  title: Attom Property API
  description: API for accessing property data from Attom
  version: 1.0.0
paths:
  /property/address:
    get:
      summary: List properties by zip code
      security:
        - sigv4: []
      description: Retrieve a list of properties based on the provided zip code, page, and limit.
      parameters:
        - name: postalcode
          in: query
          required: true
          schema:
            type: string
          description: The zip code to filter properties by.
        - name: page
          in: query
          required: false
          schema:
            type: integer
            default: 1
          description: The page number for pagination.
        - name: pagesize
          in: query
          required: false
          schema:
            type: integer
            default: 10
          description: The number of results per page.
      responses:
        '200':
          description: A list of properties matching the criteria.
      x-amazon-apigateway-integration:
        type: http_proxy
        httpMethod: POST
        uri: https://api.gateway.attomdata.com/propertyapi/v1.0.0/property/address
        # requestParameters:
        #   integration.request.querystring.postalcode: method.request.querystring.postalcode
        #   integration.request.querystring.page: method.request.querystring.page
        #   integration.request.querystring.pagesize: method.request.querystring.pagesize
        requestHeaders:
          Accept: "'application/json'"
          apikey: "'${env.ATTOM_API_KEY}'"
        responses:
          default:
            statusCode: 200
            