name: Deploy drivestate-estatengine-backend

on:
    push:
        branches:
            - main
            - openai-proxy
jobs:
    deploy:
        name: Deploy Backend
        runs-on: ubuntu-latest

        env:
            AWS_REGION: us-east-2
            TF_VAR_stage: prod
            SERVERLESS_ACCESS_KEY: ${{secrets.SERVERLESS_ACCESS_KEY}}
        
        steps:
            - name: Checkout repo
              uses: actions/checkout@v3

            - name: Set up Python
              uses: actions/setup-python@v3
              with:
                python-version: "3.13"
            - name: Set up NodeJs
              uses: actions/setup-node@v4
             
            
            - name: Install Terraform
              uses: hashicorp/setup-terraform@v3
              with:
                terraform_version: 1.6.6
            
            - name: Configure AWS Credentials
              uses: aws-actions/configure-aws-credentials@v2
              with:
                aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
                aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
                aws-region: ${{ env.AWS_REGION }}
            - name: Serverless Deploy
              run: |
                
                export STAGE=dev
                # cd src/openai_proxy
                # mkdir package
                # pip install -r requirements.txt --target package
                # cd package
                # zip -rq ../openai_handler.zip .
                # cd ..
                # zip -gq ../openai_handler.zip openai_handler.py
                # cd ..

                # cd search_engine
                # mkdir package
                # pip install -r requirements.txt --target package
                # cd package
                # zip -rq ../search_engine.zip .
                # cd ..
                # zip -gq ../search_engine.zip search_engine.py
                # cd ../..
                
                export GPSE_API_KEY=${{ secrets.GPSE_API_KEY }}
                export GOOGLE_API_ID=${{ secrets.GOOGLE_API_ID }}
                npm i -g serverless 
                

                pip install -r requirements.txt
                sls login 
                npm install serverless-appsync-plugin ---debug
                sls package --stage $STAGE --region $AWS_REGION
                sls deploy --stage $STAGE --region $AWS_REGION